from django.urls import path

from business_os.portals import views

urlpatterns = [
    path("o/<slug:organization_slug>/dashboard/", views.admin_dashboard, name="admin-dashboard"),
    path(
        "o/<slug:organization_slug>/marketplace/", views.admin_marketplace, name="admin-marketplace"
    ),
    path("o/<slug:organization_slug>/billing/", views.admin_billing, name="admin-billing"),
    path("o/<slug:organization_slug>/website/", views.admin_website, name="admin-website"),
    path("o/<slug:organization_slug>/products/", views.admin_products, name="admin-products"),
    path(
        "o/<slug:organization_slug>/products/new/",
        views.admin_product_create,
        name="admin-products-create",
    ),
    path(
        "o/<slug:organization_slug>/products/<uuid:offering_id>/",
        views.admin_product_detail,
        name="admin-products-detail",
    ),
    path(
        "o/<slug:organization_slug>/products/<uuid:offering_id>/edit/",
        views.admin_product_edit,
        name="admin-products-edit",
    ),
    path(
        "o/<slug:organization_slug>/products/<uuid:offering_id>/archive/",
        views.admin_product_archive,
        name="admin-products-archive",
    ),
    path(
        "o/<slug:organization_slug>/products/<uuid:offering_id>/restore/",
        views.admin_product_restore,
        name="admin-products-restore",
    ),
    path(
        "o/<slug:organization_slug>/products/<uuid:offering_id>/options/new/",
        views.admin_option_create,
        name="admin-product-options-create",
    ),
    path(
        "o/<slug:organization_slug>/products/<uuid:offering_id>/options/<uuid:option_id>/edit/",
        views.admin_option_edit,
        name="admin-product-options-edit",
    ),
    path(
        "o/<slug:organization_slug>/products/<uuid:offering_id>/options/<uuid:option_id>/archive/",
        views.admin_option_archive,
        name="admin-product-options-archive",
    ),
    path(
        "o/<slug:organization_slug>/products/<uuid:offering_id>/options/<uuid:option_id>/restore/",
        views.admin_option_restore,
        name="admin-product-options-restore",
    ),
    path(
        (
            "o/<slug:organization_slug>/products/<uuid:offering_id>/"
            "options/<uuid:option_id>/values/new/"
        ),
        views.admin_option_value_create,
        name="admin-product-option-values-create",
    ),
    path(
        (
            "o/<slug:organization_slug>/products/<uuid:offering_id>/"
            "options/<uuid:option_id>/values/<uuid:value_id>/edit/"
        ),
        views.admin_option_value_edit,
        name="admin-product-option-values-edit",
    ),
    path(
        (
            "o/<slug:organization_slug>/products/<uuid:offering_id>/"
            "options/<uuid:option_id>/values/<uuid:value_id>/archive/"
        ),
        views.admin_option_value_archive,
        name="admin-product-option-values-archive",
    ),
    path(
        (
            "o/<slug:organization_slug>/products/<uuid:offering_id>/"
            "options/<uuid:option_id>/values/<uuid:value_id>/restore/"
        ),
        views.admin_option_value_restore,
        name="admin-product-option-values-restore",
    ),
    path(
        "o/<slug:organization_slug>/products/<uuid:offering_id>/variants/new/",
        views.admin_variant_create,
        name="admin-product-variants-create",
    ),
    path(
        "o/<slug:organization_slug>/products/<uuid:offering_id>/variants/<uuid:variant_id>/edit/",
        views.admin_variant_edit,
        name="admin-product-variants-edit",
    ),
    path(
        (
            "o/<slug:organization_slug>/products/<uuid:offering_id>/"
            "variants/<uuid:variant_id>/archive/"
        ),
        views.admin_variant_archive,
        name="admin-product-variants-archive",
    ),
    path(
        (
            "o/<slug:organization_slug>/products/<uuid:offering_id>/"
            "variants/<uuid:variant_id>/restore/"
        ),
        views.admin_variant_restore,
        name="admin-product-variants-restore",
    ),
    path("o/<slug:organization_slug>/categories/", views.admin_categories, name="admin-categories"),
    path(
        "o/<slug:organization_slug>/categories/new/",
        views.admin_category_create,
        name="admin-categories-create",
    ),
    path(
        "o/<slug:organization_slug>/categories/<uuid:category_id>/",
        views.admin_category_detail,
        name="admin-categories-detail",
    ),
    path(
        "o/<slug:organization_slug>/categories/<uuid:category_id>/edit/",
        views.admin_category_edit,
        name="admin-categories-edit",
    ),
    path(
        "o/<slug:organization_slug>/categories/<uuid:category_id>/archive/",
        views.admin_category_archive,
        name="admin-categories-archive",
    ),
    path(
        "o/<slug:organization_slug>/categories/<uuid:category_id>/restore/",
        views.admin_category_restore,
        name="admin-categories-restore",
    ),
    path(
        "o/<slug:organization_slug>/collections/",
        views.admin_collections,
        name="admin-collections",
    ),
    path(
        "o/<slug:organization_slug>/collections/new/",
        views.admin_collection_create,
        name="admin-collections-create",
    ),
    path(
        "o/<slug:organization_slug>/collections/<uuid:collection_id>/",
        views.admin_collection_detail,
        name="admin-collections-detail",
    ),
    path(
        "o/<slug:organization_slug>/collections/<uuid:collection_id>/edit/",
        views.admin_collection_edit,
        name="admin-collections-edit",
    ),
    path(
        "o/<slug:organization_slug>/collections/<uuid:collection_id>/archive/",
        views.admin_collection_archive,
        name="admin-collections-archive",
    ),
    path(
        "o/<slug:organization_slug>/collections/<uuid:collection_id>/restore/",
        views.admin_collection_restore,
        name="admin-collections-restore",
    ),
    path("o/<slug:organization_slug>/inventory/", views.admin_inventory, name="admin-inventory"),
    path("o/<slug:organization_slug>/orders/", views.admin_orders, name="admin-orders"),
    path("o/<slug:organization_slug>/payments/", views.admin_payments, name="admin-payments"),
    path("o/<slug:organization_slug>/analytics/", views.admin_analytics, name="admin-analytics"),
    path("o/<slug:organization_slug>/settings/", views.admin_settings, name="admin-settings"),
]
