# Generated by Django 5.2.16 on 2026-07-12 11:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_platform_staff_role(apps, schema_editor):
    auth_app_label, user_model_name = settings.AUTH_USER_MODEL.split(".")
    user_model = apps.get_model(auth_app_label, user_model_name)
    platform_role = apps.get_model("core", "PlatformRole")
    platform_role_assignment = apps.get_model("core", "PlatformRoleAssignment")

    role, _created = platform_role.objects.update_or_create(
        code="platform-administrator",
        defaults={
            "name": "Platform Administrator",
            "description": "System role for existing platform staff users.",
            "permissions": ["*"],
            "is_system": True,
            "is_active": True,
        },
    )

    for user_id in user_model.objects.filter(is_platform_staff=True).values_list("id", flat=True):
        platform_role_assignment.objects.get_or_create(
            user_id=user_id,
            role_id=role.id,
            defaults={"reason": "Backfilled from is_platform_staff during core.0002."},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'code'], name='core_platfo_is_acti_2171a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('read_only', 'Read-only'), ('controlled_write', 'Controlled write')], default='read_only', max_length=32)),
                ('reason', models.CharField(max_length=255)),
                ('ticket_reference', models.CharField(blank=True, max_length=120)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_sessions', to=settings.AUTH_USER_MODEL)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_support_sessions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_sessions', to='organizations.organization')),
            ],
        ),
        migrations.AddField(
            model_name='auditevent',
            name='support_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='core.supportsession'),
        ),
        migrations.CreateModel(
            name='PlatformRoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('starts_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_platform_role_assignments', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_platform_role_assignments', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='core.platformrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'starts_at', 'expires_at'], name='core_platfo_user_id_7c36f4_idx'), models.Index(fields=['role', 'revoked_at'], name='core_platfo_role_id_bf8a3f_idx')],
            },
        ),
        migrations.RunPython(backfill_platform_staff_role, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='supportsession',
            index=models.Index(fields=['actor', 'organization', 'expires_at'], name='core_suppor_actor_i_20bedf_idx'),
        ),
        migrations.AddIndex(
            model_name='supportsession',
            index=models.Index(fields=['organization', 'ended_at', 'expires_at'], name='core_suppor_organiz_15f1a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportsession',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('started_at'))), name='support_session_expiry_after_start'),
        ),
    ]
