# Generated by Django 5.2.16 on 2026-07-11 16:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('supported_countries', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('default_limit', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(db_index=True, max_length=80)),
                ('icon', models.CharField(default='box', max_length=80)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('navigation', models.JSONField(blank=True, default=list)),
                ('website_contributions', models.JSONField(blank=True, default=list)),
                ('dashboard_widgets', models.JSONField(blank=True, default=list)),
                ('supported_countries', models.JSONField(blank=True, default=list)),
                ('supported_industries', models.JSONField(blank=True, default=list)),
                ('release_status', models.CharField(choices=[('draft', 'Draft'), ('internal', 'Internal'), ('private_beta', 'Private beta'), ('public', 'Public'), ('deprecated', 'Deprecated'), ('retired', 'Retired')], db_index=True, default='draft', max_length=32)),
                ('visible_in_marketplace', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.bundle')),
                ('capability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='marketplace.capability')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='marketplace.module')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bundle', 'module', 'capability'), name='unique_bundle_module_capability')],
            },
        ),
        migrations.CreateModel(
            name='ModuleCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('included', models.BooleanField(default=True)),
                ('required', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_links', to='marketplace.capability')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_capabilities', to='marketplace.module')),
            ],
            options={
                'ordering': ['sort_order', 'capability__code'],
                'constraints': [models.UniqueConstraint(fields=('module', 'capability'), name='unique_module_capability')],
            },
        ),
        migrations.CreateModel(
            name='ModuleDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependency_type', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('recommended', 'Recommended'), ('conflicting', 'Conflicting')], default='required', max_length=32)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_modules', to='marketplace.module')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='marketplace.module')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('module', 'depends_on', 'dependency_type'), name='unique_module_dependency')],
            },
        ),
        migrations.CreateModel(
            name='ModuleLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=120)),
                ('included_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(max_length=40)),
                ('overage_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('capability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='marketplace.capability')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='marketplace.module')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('module', 'code'), name='unique_module_limit_code')],
            },
        ),
        migrations.CreateModel(
            name='ModulePrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('billing_period', models.CharField(default='monthly', max_length=20)),
                ('pricing_type', models.CharField(choices=[('fixed_recurring', 'Fixed recurring'), ('annual_recurring', 'Annual recurring'), ('one_time', 'One-time'), ('usage_based', 'Usage-based'), ('manual', 'Manual enterprise')], default='fixed_recurring', max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('tax_inclusive', models.BooleanField(default=False)),
                ('snapshot_metadata', models.JSONField(blank=True, default=dict)),
                ('capability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='marketplace.capability')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='marketplace.module')),
            ],
            options={
                'indexes': [models.Index(fields=['module', 'country', 'currency', 'active'], name='marketplace_module__095602_idx')],
            },
        ),
    ]
