# Generated by Django 5.2.16 on 2026-07-11 16:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('pending', 'Pending'), ('hidden', 'Hidden'), ('suspended', 'Suspended'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=32)),
                ('domain_name', models.CharField(max_length=253, unique=True)),
                ('domain_type', models.CharField(choices=[('generated', 'Generated'), ('custom', 'Custom'), ('preview', 'Preview')], default='generated', max_length=24)),
                ('domain_status', models.CharField(choices=[('requested', 'Requested'), ('dns_pending', 'DNS pending'), ('verifying', 'Verifying'), ('verified', 'Verified'), ('ssl_pending', 'SSL pending'), ('active', 'Active'), ('failed', 'Failed'), ('suspended', 'Suspended'), ('removed', 'Removed')], db_index=True, default='requested', max_length=32)),
                ('is_primary', models.BooleanField(default=False)),
                ('redirect_generated_subdomain', models.BooleanField(default=False)),
                ('redirect_mode', models.CharField(choices=[('none', 'None'), ('www', 'Redirect to www'), ('non_www', 'Redirect to non-www')], default='none', max_length=24)),
                ('verification_method', models.CharField(blank=True, max_length=80)),
                ('verification_token', models.CharField(blank=True, max_length=160)),
                ('dns_records', models.JSONField(blank=True, default=list)),
                ('ssl_status', models.CharField(blank=True, max_length=80)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.facility')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='websites.website')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'domain_status'], name='websites_we_organiz_64bd88_idx'), models.Index(fields=['domain_name', 'domain_status'], name='websites_we_domain__f80c00_idx')],
            },
        ),
    ]
