# Generated by Django 5.2.16 on 2026-07-11 16:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('code', models.SlugField(max_length=80)),
                ('facility_type', models.CharField(choices=[('online', 'Online store'), ('retail', 'Retail store'), ('warehouse', 'Warehouse'), ('office', 'Office')], default='online', max_length=40)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('timezone', models.CharField(default='Asia/Dubai', max_length=80)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('operating_hours', models.JSONField(blank=True, default=dict)),
                ('public_visibility', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('pending', 'Pending'), ('hidden', 'Hidden'), ('suspended', 'Suspended'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('legal_name', models.CharField(blank=True, max_length=220)),
                ('country', models.CharField(choices=[('AE', 'United Arab Emirates'), ('IN', 'India')], default='AE', max_length=2)),
                ('default_currency', models.CharField(default='AED', max_length=3)),
                ('timezone', models.CharField(default='Asia/Dubai', max_length=80)),
                ('default_locale', models.CharField(default='en', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('pending', 'Pending'), ('hidden', 'Hidden'), ('suspended', 'Suspended'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=32)),
                ('tax_registration_number', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['slug', 'status'], name='organizatio_slug_37acf2_idx'), models.Index(fields=['country', 'status'], name='organizatio_country_cdd3c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('pending', 'Pending'), ('hidden', 'Hidden'), ('suspended', 'Suspended'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=32)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('membership_status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=32)),
                ('is_owner', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.facility')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
        ),
        migrations.AddField(
            model_name='facility',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='organizations.organization'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('pending', 'Pending'), ('hidden', 'Hidden'), ('suspended', 'Suspended'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=32)),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.facility')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('pending', 'Pending'), ('hidden', 'Hidden'), ('suspended', 'Suspended'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=32)),
                ('resource', models.CharField(max_length=120)),
                ('action', models.CharField(max_length=80)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.facility')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='organizations.role')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('pending', 'Pending'), ('hidden', 'Hidden'), ('suspended', 'Suspended'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.facility')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to='organizations.membership')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_links', to='organizations.role')),
            ],
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['organization', 'user', 'membership_status'], name='organizatio_organiz_42e4e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_membership_per_organization_user'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['organization', 'status'], name='organizatio_organiz_e97dc9_idx'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_facility_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_role_code_per_org'),
        ),
        migrations.AddIndex(
            model_name='permissiongrant',
            index=models.Index(fields=['organization', 'resource', 'action'], name='organizatio_organiz_8c7932_idx'),
        ),
        migrations.AddConstraint(
            model_name='permissiongrant',
            constraint=models.UniqueConstraint(fields=('organization', 'role', 'resource', 'action'), name='unique_permission_grant_per_role'),
        ),
        migrations.AddConstraint(
            model_name='membershiprole',
            constraint=models.UniqueConstraint(fields=('organization', 'membership', 'role'), name='unique_membership_role_per_org'),
        ),
    ]
